Fix Packer workflows by handling missing webapp.zip

diff --git a/.github/workflows/packer-build.yml b/.github/workflows/packer-build.yml
--- a/.github/workflows/packer-build.yml
+++ b/.github/workflows/packer-build.yml
@@ -17,7 +17,6 @@ jobs:
         with:
           version: latest
 
-      
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
@@ -25,6 +24,11 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
 
+      - name: Ensure WebApp.zip Exists
+        run: |
+          if [ ! -f "webapp.zip" ]; then echo "Error: webapp.zip does not exist!"; exit 1; fi
+
       - name: Build Packer Configuration
         run: |
           packer build packer/machine-image.pkr.hcl
+          
diff --git a/.github/workflows/packer-validate.yml b/.github/workflows/packer-validate.yml
--- a/.github/workflows/packer-validate.yml
+++ b/.github/workflows/packer-validate.yml
@@ -23,10 +23,11 @@ jobs:
 
       - name: Format Check
         run: |
-          packer fmt packer/machine-image.pkr.hcl
+          packer fmt -check packer/machine-image.pkr.hcl
 
       - name: Validate Packer Configuration
         run: |
+          if [ ! -f "webapp.zip" ]; then echo "Error: webapp.zip does not exist!"; exit 1; fi
           packer validate packer/machine-image.pkr.hcl
-
+          
       
